# repo_url|ref|dest_dir
https://github.com/aosp-mirror/kernel_common.git|android14-6.1|kernel_common
https://github.com/postmarketOS/pmaports.git|master|pmaports
https://android.googlesource.com/kernel/devices/google/shusky|android-gs-shusky-5.15-android14-qpr3|google-shusky-kernel-devices
https://android.googlesource.com/device/google/shusky|android-14.0.0_r75|google-shusky-device
